spring.datasource.url=${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:will}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
